"""Add progress tracking tables

Revision ID: 13f5ea8f8e64
Revises: e879067a599e
Create Date: 2025-10-11 21:56:46.337894

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13f5ea8f8e64"
down_revision: Union[str, None] = "e879067a599e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "completion_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("completed_lessons", sa.Integer(), nullable=False),
        sa.Column("total_lessons", sa.Integer(), nullable=False),
        sa.Column(
            "total_time_spent", sa.Integer(), nullable=False, comment="Time in minutes"
        ),
        sa.Column("is_certificate_issued", sa.Boolean(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of creation of the record",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_progress_course_id"),
        "course_progress",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_progress_status"), "course_progress", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_course_progress_user_id"), "course_progress", ["user_id"], unique=False
    )
    op.create_table(
        "lesson_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_progress_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completion_percentage", sa.Integer(), nullable=False),
        sa.Column(
            "time_spent", sa.Integer(), nullable=False, comment="Time in minutes"
        ),
        sa.Column("watch_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_position",
            sa.Integer(),
            nullable=False,
            comment="Last position in seconds",
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Date and time of creation of the record",
        ),
        sa.ForeignKeyConstraint(
            ["course_progress_id"], ["course_progress.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_progress_course_progress_id"),
        "lesson_progress",
        ["course_progress_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_progress_lesson_id"),
        "lesson_progress",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_progress_user_id"), "lesson_progress", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lesson_progress_user_id"), table_name="lesson_progress")
    op.drop_index(op.f("ix_lesson_progress_lesson_id"), table_name="lesson_progress")
    op.drop_index(
        op.f("ix_lesson_progress_course_progress_id"), table_name="lesson_progress"
    )
    op.drop_table("lesson_progress")
    op.drop_index(op.f("ix_course_progress_user_id"), table_name="course_progress")
    op.drop_index(op.f("ix_course_progress_status"), table_name="course_progress")
    op.drop_index(op.f("ix_course_progress_course_id"), table_name="course_progress")
    op.drop_table("course_progress")
    # ### end Alembic commands ###
